#24 fix auth services
BOOK-TALK/Back pull request #29
Opened 2024-08-01 15:32 UTC by chanwoo7

## #️⃣ 연관된 이슈
- [ ] #24

## 📝 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요
- [ ] 세션 확인용 세션 정보 출력 API 작성
- [ ] RequestLogger 수정
- [ ] Postman 테스트

### 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)
AuthService 클래스의 로그인 로직에서, 세션에 SecurityContext를 저장하는 부분이 누락된 것을 확인하여 해당 로직을 추가했습니다.

이후 Postman에서 회원 관리에 해당하는 4개의 API들이 JSESSIONID를 기반으로 정상적으로 동작하는 것을 확인했습니다.

추가로, RequestLogger에서 paramIter의 value를 출력할 때 데이터가 아닌 클래스(타입명)를 출력하도록 되어 있어서, 데이터를 출력하는 방식으로 수정했습니다.

2024-08-03 00:22 UTC, hyeesw requested changes

2024-08-03 00:22 UTC, hyeesw commented on src/main/java/com/book/backend/global/log/RequestLogger.java
> +                sb.append(key).append(": ").append(value);
운영서버 로그에 요청 내용이 찍히는건 보안상 좋지 않다고 판단해서 일부러 타입만 공개하도록 해둔거였어! 
@Valid 어노테이션에서 값 형식을 제한할 수 있으니 타입까지만 출력해도 디버깅하는덴 무리 없다고 생각해

2024-08-03 10:39 UTC, chanwoo7 commented on src/main/java/com/book/backend/global/log/RequestLogger.java
> +                sb.append(key).append(": ").append(value);
오케이 다시 원래대로 수정할게!

2024-08-05 11:23 UTC, hyeesw approved these changes

2024-08-05 11:48 UTC, merged