#25 genre data initialization
BOOK-TALK/Back pull request #33
Opened 2024-08-02 13:45 UTC by chanwoo7

## #️⃣ 연관된 이슈
- [x] #25

## 📝 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요
- [x] 장르 테이블에 KDC 필드 추가
- [x] 장르 데이터 세팅
- [x] 장르 서비스, 컨트롤러 코드 작성
- [x] 2자리 KDC 번호로 장르 검색하면 책 목록 리턴하는 컨트롤러 구현

### 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)
장르를 부모 여부에 따라 Level 1(=대주제)과 Level 2(=중주제)로 구분 가능합니다.
이에 따라 중주제의 하위로 책 리스트를 갖도록 구현했습니다.

그리고 data.sql을 사용하여 장르 데이터를 세팅했습니다.

이후 필요한 컨트롤러 코드를 작성했습니다.

2024-08-03 00:55 UTC, hyeesw requested changes

2024-08-03 00:55 UTC, hyeesw commented on src/main/java/com/book/backend/domain/genre/controller/GenreController.java
> +
소수제(2자리) 이외에도 대주제(1자리)로 책 검색하는 controller 는 이후에 작성할 예정이야?!

2024-08-03 10:38 UTC, chanwoo7 commented on src/main/java/com/book/backend/domain/genre/controller/GenreController.java
> +
아 맞다 그 컨트롤러도 같이 추가할게!

2024-08-05 11:47 UTC, hyeesw submitted a review, later dismissed

2024-08-05 11:51 UTC, merged