#52 JWT 기반 인증 구현
BOOK-TALK/Back pull request #53
Opened 2024-08-14 04:12 UTC by chanwoo7

## #️⃣ 연관된 이슈
- [ ] #52

## 📝 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요
- [ ] 기존 세션 기반 인증 로직 삭제, JWT 기반 인증 방식으로 변경
- [ ] 미인증 유저에 대한 접근 제한 핸들링
- [ ] Access Token 기반 검증 로직 구현
- [ ] Refresh Token 갱신 로직 구현
- [ ] Refresh Token 기반 Access Token 갱신 로직 구현

### 스크린샷 (선택)

https://github.com/user-attachments/assets/91cfd266-33ee-4f3c-8c40-7c310e9084af

등록된 회원 정보로 로그인을 시도합니다. 
성공 시 Access Token과 Refresh Token이 발급되며, 발급된 Access Token을 통해 인증이 필요한 다른 API에 접근할 수 있습니다.

<br>

https://github.com/user-attachments/assets/179434ba-8356-4ef9-adb9-ccfbed385055

영상처럼 요청 헤더에 Authorization 키를 추가하고, `Bearer [Access Token 값]`과 같이 입력하면 API에 접근 가능합니다.

## 💬 리뷰 요구사항(선택)
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 1. `.env` 파일이 변경되었습니다. 노션을 확인해주세요!
> 2. 일단 임시로 Access Token의 유효 시간은 1시간으로, Refresh Token의 유효 시간은 2주로 설정했습니다.
>   - 개발 단계이므로 Access Token의 기한을 길게 설정했으며, 향후 운영 시 수정할 계획입니다.
> 3. 현재 Refresh Token 기반으로 Access Token를 갱신하는 로직은 아직 개발 중에 있으나, Access Token을 기반으로 API에 정상적으로 접근이 가능한 상태입니다.
> 4. 기타 수정해야 할 사항이 있다면 알려주시면 감사하겠습니다!

2024-08-14 09:36 UTC, hyeesw requested changes

2024-08-14 09:36 UTC, hyeesw commented on src/main/java/com/book/backend/domain/auth/service/JwtAuthenticationFilter.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
swagger 외의 다른 api 에 접근할 때마다 보안필터를 재사용해서 동일한 인증을 다시 하지 않도록 하는거 맞나??

2024-08-14 09:36 UTC, hyeesw commented on src/main/java/com/book/backend/util/RequestWrapper.java
RequestWrapper.java 는 jwt Authorization 관련해서만 사용할 수 있는 클래스인가?? 혹시 재사용할 수 있는 상황이 있나 싶어서!

2024-08-14 09:37 UTC, hyeesw commented
나도 kakao login 되는지 테스트 해볼 수 있나??

2024-08-14 10:00 UTC, chanwoo7 commented on src/main/java/com/book/backend/domain/auth/entity/RefreshToken.java
> +    // TODO: 향후 Redis 사용 고려
음 Redis(또는 DB)에 저장하는 방식이 더 보안성이 높을 것 같다고 생각했는데 그 방식이 더 나으려나?? 조작 여부만 확인하는 방식이 구현하기는 더 쉬울 것 같긴 해

2024-08-14 10:09 UTC, chanwoo7 commented on src/main/java/com/book/backend/domain/auth/service/JwtAuthenticationFilter.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
음 정확하게는 UsernamePasswordAuthenticationFilter.class를 거치기 전에(즉 기본적인 인증 필터를 거치기 전에) JWT 토큰을 검증하기 위한 필터를 정의한 거야!

Swagger 관련 경로들은 JWT 토큰으로 검증할 필요도 없고, 이 필터를 거치게 되면 Swagger에서 제대로 API 목록들이 보여지지 않아서 이 필터를 바로 넘기도록 따로 설정한거야.

2024-08-14 10:22 UTC, chanwoo7 commented on src/main/java/com/book/backend/util/RequestWrapper.java
음 일단 이 클래스를 작성한 목적은 HTTP Request body를 선제적으로 읽고 캐시하기 위함이었어! 만약 request body를 여러번 읽어야 할 일이 있을 때 이 클래스를 재사용할 수 있을 거 같아.

나는 처음에 JwtAuthenticationFilter 작성할 때 request body를 여러 번 읽는 것 때문에 JSON 파싱 오류가 발생해서 따로 내용을 캐시해둘 용도로 이 클래스를 추가한 거였어. 만약 HttpServletRequest를 파라미터로 받는 필터를 개발할 때 비슷한 오류가 발생한다면 이 클래스로 래핑하면 될 거 같아!

2024-08-14 10:24 UTC, chanwoo7 commented
> 나도 kakao login 되는지 테스트 해볼 수 있나??

음 아마 .env에 callback 링크를 설정해둬서 가능할 것 같아! 내가 저번에 올린 카카오 OAuth PR에 있는 링크 참고해주면 될 듯

2024-08-14 12:18 UTC, hyeesw commented on src/main/java/com/book/backend/domain/auth/entity/RefreshToken.java
> +    // TODO: 향후 Redis 사용 고려
맞아맞아 근데 모든 refresh 토큰을 저장하는게 아니라 탈취된(폐기해야되는) 토큰을 DB에 블랙리스트 마냥 저장하는거여서 지금은 조작여부만 확인하는게 좋을 것 같어!

2024-08-14 12:21 UTC, hyeesw commented on src/main/java/com/book/backend/util/RequestWrapper.java
아하 오키 혹시나 아래 상황이 생기면 재사용 해볼게

> request body를 여러번 읽어야 할 일이 있을 때

> HttpServletRequest를 파라미터로 받는 필터를 개발할 때

2024-08-15 06:12 UTC, hyeesw approved these changes

2024-08-15 06:12 UTC, merged