#46 opentalk
BOOK-TALK/Back pull request #59
Opened 2024-08-17 13:05 UTC by hyeesw

## #️⃣ 연관된 이슈
- [ ] #45 
- [ ] #50

## 📝 작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요
- 채팅 불러오기
- [x] message 테이블 createdAt 인덱싱
- [x] opentalkId 를 입력으로 받으면, message 테이블에서 해당 opentalkId 의 채팅을 createdAt 최신순으로 N 개 조회해서 반환
- [x] message 테이블에서 opentalkId 칼럼 기준으로 페이지네이션
</br>

-  채팅 작성하기
- [x] 입력 : opentalkId, loginId, content -> message 테이블에 저장하기
- [x] createdAt 은 서버 측에서 측정.

### 스크린샷 (선택)
<img src="https://github.com/user-attachments/assets/d18641cd-7f7f-4c0a-8c58-186c3d804ad6" width="30%">

## 💬 리뷰 요구사항(선택)
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 채팅창에서 위로 스크롤할 때마다 페이지네이션 처리하도록 구현해서 getChat API는 opentalkId, pageNo, pageSize를 입력으로 받습니다.

2024-08-18 14:49 UTC, chanwoo7 requested changes
STOMP나 다른 소켓 통신 세팅 없이 JPA 기반으로 저장, 조회 로직을 구현한 거 같은데 아직 추가되지 않은 건가? 만약 의도한 거라면 소켓을 사용하지 않은 이유가 궁금해.

2024-08-18 14:51 UTC, chanwoo7 commented
그리고 이번 PR에서는 미디어 저장 없이 content에 텍스트만 들어오도록 한정한 거 같은데 맞아??

2024-08-18 14:55 UTC, chanwoo7 commented
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/d484b921-a9b0-477a-9131-3980b08275e5">
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/1c99f67e-64f9-46b7-8d5c-6c3f62ef705c">

추가로 오픈톡 불러오기 테스트해봤는데 더미데이터에는 opentalk_id 1에 해당하는 메시지가 많은 것 같은데 2개밖에 나오지 않는 것 같아!

2024-08-18 15:04 UTC, chanwoo7 commented
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/b716a609-a672-42e1-b183-1853ec95bfd1">
그리고 RequestParam이나 RequestBody 중 하나로 통일하는 게 좋을 것 같아.
이 API는 검색이나 필터링을 수행하는 게 아니기도 하고, content에 들어갈 내용이 많을 것 같아서 쿼리 파라미터(RequestParam)보다는 RequestBody로 통일하는 게 좋을 것 같은데 어때?

2024-08-18 15:15 UTC, chanwoo7 commented
그리고 각 API에 statusCode가 빠져있는 것 같은데, `return new ResponseEntity<>(response, HttpStatus.OK);` 형식 말고 `return responseTemplate.success([reponse DTO명], HttpStatus.OK);`로 통일하는 게 좋을 것 같아!

2024-08-18 15:29 UTC, hyeesw commented
**아래 수정 사항 내일 전체회의 전에 push 해둘게!**

STOMP나 다른 소켓 통신 세팅 없이 JPA 기반으로 저장, 조회 로직을 구현한 거 같은데 아직 추가되지 않은 건가? 만약 의도한 거라면 소켓을 사용하지 않은 이유가 궁금해.
> 아.. 게시판 느낌이라서 웹소켓 통신이 필요 없을 거라고 생각했었는데, 잘못 생각했던 것 같아 Http 통신은 단방향 통신이라서 클라이언트가 요청을 보내지 않으면 서버로부터 응답을 받을 수 없는 구조인데, 다른 사용자의 채팅을 실시간으로 받으려면 웹소켓(stomp)으로 구현해야겠다.

그리고 이번 PR에서는 미디어 저장 없이 content에 텍스트만 들어오도록 한정한 거 같은데 맞아??
> 맞아 일단 이렇게 구현해놨어 나중에 프사 같이 처리하면서 이미지도 저장하는 로직 추가해야될 것 같아

오픈톡 불러오기 테스트 페이지네이션에 문제가 있는듯
> 엉엉 확인해볼게

그리고 RequestParam이나 RequestBody 중 하나로 통일하는 게 좋을 것 같아. 
> 아 이거 swagger 문서 잘못 써서 request param 이 같이 들어갔다. 원래 request body 만 있는건데 수정할게

return responseTemplate.success([reponse DTO명], HttpStatus.OK);로 통일하는 게 좋을 것 같아!
> 오케이 이거로 수정할게

2024-08-20 06:53 UTC, hyeesw commented
- [ ] 오픈톡 stomp 통신으로 변경
- [ ] S3에 이미지 저장 (프사, 오픈톡 채팅)
- [ ] 오픈톡 채팅 저장 API : RequestParam 삭제
- [ ] 오픈톡 response 형식 response 반환 코드 수정
- [ ] 오픈톡 채팅 불러오기 페이지네이션 문제 -> pageSize가 0부터 입력돼서 1 넣었을 때 그렇게 보인 것 같아!

맨 위에 2개는 다른 이슈로 파서 작업하려고!

2024-08-20 06:56 UTC, merged